### ISSUE TITLE
Failed upload b/c Infura fails to parse files

### ISSUE THREAD

**Issue by jasikpark** [agentofuser/ipfs-deploy#27]
<img width="1389" alt="Screenshot 2019-05-15 01 00 57" src="https://user-images.githubusercontent.com/10626596/57751960-fa75fe00-76ac-11e9-9623-294f88f09b16.png">
i'm not quite sure what's wrong.

versions:
node: 10.15.3
ipfs-deploy installed via yarn
hugo 0.55.5 generated website

**Comment by agentofuser** [comment]
Hi @jasikpark. Thanks for reporting! I couldn't tell just from the stacktrace what might be wrong. I've experience and also seen reports of instability in the Infura IPFS API. Sometimes it just fails for no reason, then a little later it works. Are you getting this error consistently every time?

**Comment by jasikpark** [comment]
I tried it a few times before I made the issue - i’ll try it again soon.  

Caleb Jasik  
calebjasik@jasik.xyz(mailto:calebjasik@jasik.xyz)
https://jasik.xyz

**Comment by jasikpark** [comment]
Ok. I tried again, this time from my local library's wifi. It yet again failed. With the same error. 
Could it be that somehow the parsing is failing in a weird way b/c of how my files are named somehow??

**Comment by agentofuser** [comment]
@jasikpark do you get that error if you try to deploy a minimal site like the "hello worlds" example in https://interplanetarygatsby.com/ipfs-deploy ?

**Comment by jasikpark** [comment]
https://ipfs.infura.io/ipfs/QmY6fXqECSVEYkLXsvPZHEgu9Hdxwwdy9eWqjrvJhXHLJn

yeah, it's some particular thing with the content I am uploading... I'm trying to upload the current build of https://github.com/jasikpark/jasik-xyz

**Comment by agentofuser** [comment]
@jasikpark so it turns out it's not something with the content. I'm getting that too at random. Infura's IPFS service is just very spotty. This "fixed" it for me:

I define this function on my shell:

```bash
# ~/.bashrc
function retryuntilsuccess() {
  until $*; do sleep 2; done; echo Done
}
```

Then run:

```bash
retryuntilsuccess ipd
```

Eventually it goes through. ¯\_(ツ)_/¯

**Comment by agentofuser** [comment]
Redirecting infura stability issues to this thread on their forum: https://community.infura.io/t/ipfs-v0-4-21-update/647/3. Feel free to start a new issue if there is a problem which appears to come from ipfs-deploy. Thanks!

**Comment by jasikpark** [comment]
thanks for the update!!

Caleb Jasik  
calebjasik@jasik.xyz(mailto:calebjasik@jasik.xyz)
https://jasik.xyz
