### ISSUE TITLE
Could not reach port xxxx from outside

### ISSUE THREAD

**Issue by i001962** [agentofuser/ipfs-deploy#28]
I'm getting a port unreachable error when trying to use the the api. Looking for some pointers rather than reporting an issue here.

This is the call I'm making from a nodejs app:

```
async function puttoifps() {
    try {
      const deployOptions = {
        publicDirPath: 'public',
        // siteDomain: 'ipfs.infura.io/ipfs/',
        remotePinners: 'pinata',
       // port: '8080',
        credentials: {
          pinata: {
            apiKey: 'my api key',
            secretApiKey: 'my secret',
          },
        },
      }
      return deploy(deployOptions)
    } catch (e) { console.log('error wtf happened?', e)}
  };
```
Here is there error message:
✔ 🚚 public weighs 25.0 MiB.
✔ ☎️  Connected to temporary local IPFS node.
✖ 💔 Could not reach port 4002 from the outside :(
ℹ 💡 Please forward it or try a different one with the --port option.

  Error: Could not reach port 4002 from the outside
  
  - index.js:203 IPFS.node.on
    [gatsby-plugin-crypowerk-blockchain]/[@agentofuser]/ipfs-deploy/index.js:203    :16
  
  - next_tick.js:81 processTicksAndRejections
    internal/process/next_tick.js:81:5

I've tried changing the port in the config but that hasn't worked. I don't think it's a firewall issue on my side as those ports are open. 

Any suggestions or pointers would be appreciated. - Kevin

**Comment by i001962** [comment]
Update -  I tried a few things without luck. One of which was trying to run this from the terminal with the defaults to pin it to infura. Turns out I couldn't get it to work from the terminal either but with a different error.

>pfs-deploy public/
✔ 🚚 public/ weighs 25.0 MiB.
✖ 💔 Uploading to Infura didn't work.

  ┌──────────────────────────────────────────────────────────────────────────┐
  │                                                                          │
  │ {                                                                        │
  │    "name": "SyntaxError",                                                │
  │    "className": "SyntaxError",                                           │
  │    "message": "Unexpected token G in JSON at position 0",                │
  │    "superclasses": ["Error", "Object"],                                  │
  │    "enumerableFields": {},                                               │
  │    "stack": [                                                            │
  │      "SyntaxError: Unexpected token G in JSON at position 0",            │
  │      "at JSON.parse (<anonymous>)",                                      │
  │      "at streamToValue                                                   │
  │ (/Users/kmm/.config/yarn/global/node_modules/ipfs-http-client/src/utils/ │
  │ stream-to-json-value.js:25:18)",                                         │
  │      "at concat                                                          │
  │ (/Users/kmm/.config/yarn/global/node_modules/ipfs-http-client/src/utils/ │
  │ stream-to-value.js:12:22)",                                              │
  │      "at ConcatStream.<anonymous>                                        │
  │ (/Users/kmm/.config/yarn/global/node_modules/ipfs-http-client/node_modul │
  │ es/concat-stream/index.js:32:43)",                                       │
  │      "at ConcatStream.emit (events.js:202:15)",                          │
  │      "at finishMaybe                                                     │
  │ (/Users/kmm/.config/yarn/global/node_modules/readable-stream/lib/_stream │
  │ _writable.js:620:14)",                                                   │
  │      "at afterWrite                                                      │
  │ (/Users/kmm/.config/yarn/global/node_modules/readable-stream/lib/_stream │
  │ _writable.js:466:3)",                                                    │
  │      "at processTicksAndRejections                                       │
  │ (internal/process/next_tick.js:76:17)"                                   │
  │    ]                                                                     │
  │ }                                                                        │
  │

**Comment by agentofuser** [comment]
Hi, thanks for reporting! For the Infura error, the "Syntax Error" name is misleading, it's actually a random error that we've been observing due to instability in the Infura API.

So far this has worked for me: https://github.com/agentofuser/ipfs-deploy/issues/27#issuecomment-493696039

Basically I wrote bash function to keep retrying and it eventually goes through. If this keeps happening I might consider building the retry into ipfs-deploy itself.

---

For the port-reachability case, if you do `ipd -p pinata` from the command-line (assuming credentials are set) what do you see?

**Comment by i001962** [comment]
Thanks for the response @agentofuser.
Running from the command-line gave me a similar error (on various ports I tried):
> ipd -p pinata

ℹ 🤔 No path argument specified. Looking for common ones…
✔ 📂 Found local public directory. Deploying that.
✔ 🚚 public weighs 25.0 MiB.
✔ ☎️  Connected to temporary local IPFS node.
✖ 💔 Could not reach port 4002 from the outside :(
ℹ 💡 Please forward it or try a different one with the --port option.
(node:31023) UnhandledPromiseRejectionWarning: Error: Could not reach port 4002 from the outside
    at IPFS.node.on (/Users/kmm/.config/yarn/global/node_modules/@agentofuser/ipfs-deploy/index.js:203:16)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:31023) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:31023) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by i001962** [comment]
Looks like I need to forward a port to use pinata.

'One last config: to deploy to Pinata, you’ll need to forward port 4002 on your router to your machine.'    from https://interplanetarygatsby.com/ipfs-deploy/

Now I'm wondering how to use infura with an authenticated account. Is there a way to send credentials for infura that you know of in this package?

thanks

**Comment by agentofuser** [comment]
>✖ 💔 Could not reach port 4002 from the outside :(
>ℹ 💡 Please forward it

Hm, yeah, the manual port forwarding thing could use a little more emphasis.

Hopefully the need will go away soon though, as Pinata is working on HTTP upload and js-ipfs is working on NAT traversal.

Did the upload work after forwarding the port?

---

[Infura doesn't have authenticated uploads yet](https://community.infura.io/t/how-often-do-you-garbage-collect-files-on-your-ipfs-node-and-how-long-will-a-file-persist-after-upload/44/3?u=agentofuser), though it's in their plans.

**Comment by i001962** [comment]
No, I didn’t want to mess with the router. 

Thanks for the info.
