### ISSUE TITLE
Upload to Infura doesn't work, results in gateway timeouts on GET

### ISSUE THREAD

**Issue by skddc** [agentofuser/ipfs-deploy#31]
I just tried deploying a site with the default settings, and after telling me that everything was uploaded and pinned, I only get gateway timeouts from the `ipfs.infura.io` Web gateway. Anyone else had this issue before?

**Comment by agentofuser** [comment]
Yeah they have some serious stability issues :/

**Comment by skddc** [comment]
Ah, OK. Thanks for the quick reply.

**Comment by agentofuser** [comment]
If running into issues with Infura, please let them know here: https://community.infura.io/t/ipfs-v0-4-21-update/647/3. Closing this for now, feel free to start a new one in case there's a problem on ipfs-deploy's end. Thanks!
