### ISSUE TITLE
Cloudflare deploy doesn't work with subdomain

### ISSUE THREAD

**Issue by jlelse** [agentofuser/ipfs-deploy#5]
When I try to deploy with Cloudflare to a subdomain, I get the following error:
`Error: zone ipfs.mywebsite.tld couldn't be found`

**Comment by olizilla** [comment]
Oooh... I think `zone` here needs to the root domain

https://github.com/agentofuser/ipfs-deploy/blob/823b1dc53dbea7945b737ea55b3222043604cd0c/index.js#L139-L143

so in the example given, I think 

```yaml
zone: 'mywesite.tld'
record: 'ipfs.mywebsite.tld'
```

**Comment by agentofuser** [comment]
Yeah, there isn't support for subdomain dnslink right now, but it's definitely something I want to support. I'll look into it shortly. I also take PRs if anyone wants to take a stab :)

**Comment by agentofuser** [comment]
Note that although `IPFS_DEPLOY_CLOUDFLARE__DOMAIN` is still supported for top-level domains, to use the subdomain you have to explictly use the `__ZONE` and `__RECORD` fields.

From the readme:

```bash
# cloudflare dns info
IPFS_DEPLOY_CLOUDFLARE__ZONE=agentofuser.com
IPFS_DEPLOY_CLOUDFLARE__RECORD=_dnslink.mysubdomain.agentofuser.com
```
